/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/archives/refresh/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 刷新所有 VUP 的直播归档（默认拉取最近分页）。
         * @description 刷新所有 VUP 的直播归档（默认拉取最近分页）
         */
        get: operations["refresh_all_live_archives"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archives/refresh/{mid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 刷新指定 VUP 的直播归档（默认拉取最近分页）。
         * @description 刷新指定 VUP 的直播归档（默认拉取最近分页）
         */
        get: operations["refresh_live_archives"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archives/refresh_full/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 刷新所有 VUP 的全部直播归档。
         * @description 刷新所有 VUP 的全部直播归档
         */
        get: operations["refresh_all_live_archives_full"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archives/refresh_full/{mid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 刷新指定 VUP 的全部直播归档。
         * @description 刷新指定 VUP 的全部直播归档
         */
        get: operations["refresh_live_archives_full"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live_records/all/{year}/{week}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取指定 ISO 周的全部直播记录。
         * @description 获取指定 ISO 周的全部直播记录
         */
        get: operations["get_live_records_from_db"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live_records/available_weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有有直播记录的 ISO 周列表。
         * @description 获取所有有直播记录的 ISO 周列表
         */
        get: operations["get_available_weeks_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live_records/{mid}/{year}/{week}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取指定 VUP 在指定 ISO 周的直播记录。
         * @description 获取指定 VUP 在指定 ISO 周的直播记录
         */
        get: operations["get_live_records_by_mid_from_db"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live_tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有直播标签。
         * @description 获取全部直播标签
         */
        get: operations["get_all_live_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live_tag_meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有直播标签元信息。
         * @description 获取全部直播标签元信息
         */
        get: operations["get_all_live_tag_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有预约记录。
         * @description 获取所有预约记录
         */
        get: operations["get_all_reservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/{mid}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取指定 VUP 的最新日程表。
         * @description 获取指定 VUP 的最新日程表
         */
        get: operations["get_schedule_latest_from_db"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/{mid}/{year}/{week}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取指定 VUP 指定 ISO 周的日程表。
         * @description 获取指定 VUP 指定 ISO 周的日程表
         */
        get: operations["get_schedule_from_db"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有VUP。
         * @description 获取全部VUP信息
         */
        get: operations["get_all_vup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vup_meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有 VUP 元信息。
         * @description 获取全部 VUP 元信息
         */
        get: operations["get_all_vup_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/{mid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 使用 LLM 将最新日程表转换为直播记录。
         * @description 使用 LLM 将最新日程表转换为直播记录
         */
        get: operations["transform_latest_schedule_to_live_records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 直播归档刷新返回结构。 */
        ArchivesRefreshResponse: {
            /** @description 结果提示信息。 */
            message: string;
            /** @description 是否刷新成功。 */
            success: boolean;
        };
        /** @description ISO 周信息 */
        IsoWeekTz: {
            /** Format: int32 */
            week: number;
            /** Format: int32 */
            year: number;
        };
        LiveRecordDto: {
            cover_url?: string | null;
            /** Format: int64 */
            duration_seconds?: number | null;
            /** Format: date-time */
            end_time?: string | null;
            guest_mids: number[];
            /** Format: uuid */
            id: string;
            is_reservation?: boolean | null;
            live_id_bili?: string | null;
            /** Format: int32 */
            live_type: number;
            /** Format: int64 */
            mid: number;
            /** Format: int64 */
            room_id?: number | null;
            /** Format: date-time */
            start_time: string;
            /** Format: int32 */
            status: number;
            title: string;
        };
        LiveTagDto: {
            is_active?: boolean | null;
            name: string;
            /** Format: int32 */
            sort_order?: number | null;
            /** Format: int64 */
            tag_id: number;
        };
        LiveTagMetaDto: {
            color?: string | null;
            /** Format: int32 */
            config_version?: number | null;
            icon?: string | null;
            /** Format: int64 */
            tag_id: number;
        };
        ScheduleDto: {
            /** Format: uuid */
            id: string;
            id_str: string;
            /** Format: int32 */
            iso_week: number;
            /** Format: int32 */
            iso_year: number;
            /** Format: int64 */
            mid: number;
            /** Format: date-time */
            published_at: string;
            /** Format: date */
            schedule_end: string;
            /** Format: date */
            schedule_start: string;
            schedule_url: string;
            summary?: string | null;
        };
        VupDto: {
            face_url_bili: string;
            /** Format: int64 */
            mid: number;
            name: string;
            nick_name_bili: string;
            /** Format: int64 */
            room_id: number;
            /** Format: int64 */
            sid?: number | null;
            sign: string;
        };
        VupMetaDto: {
            color?: string | null;
            /** Format: int32 */
            config_version?: number | null;
            /** Format: int64 */
            mid: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refresh_all_live_archives: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刷新结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivesRefreshResponse"];
                };
            };
        };
    };
    refresh_live_archives: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VUP 的 mid */
                mid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刷新结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivesRefreshResponse"];
                };
            };
        };
    };
    refresh_all_live_archives_full: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刷新结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivesRefreshResponse"];
                };
            };
        };
    };
    refresh_live_archives_full: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VUP 的 mid */
                mid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刷新结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivesRefreshResponse"];
                };
            };
        };
    };
    get_live_records_from_db: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 年 */
                year: number;
                /** @description 周序号（ISO） */
                week: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指定周的直播记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveRecordDto"][];
                };
            };
        };
    };
    get_available_weeks_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 所有有直播记录的 ISO 周列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IsoWeekTz"][];
                };
            };
        };
    };
    get_live_records_by_mid_from_db: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VUP 的 mid */
                mid: number;
                /** @description 年 */
                year: number;
                /** @description 周序号（ISO） */
                week: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指定 VUP 指定周的直播记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveRecordDto"][];
                };
            };
        };
    };
    get_all_live_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 直播标签列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveTagDto"][];
                };
            };
        };
    };
    get_all_live_tag_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 直播标签元信息列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveTagMetaDto"][];
                };
            };
        };
    };
    get_all_reservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 预约记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveRecordDto"][];
                };
            };
        };
    };
    get_schedule_latest_from_db: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VUP 的 mid */
                mid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 最新日程表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleDto"];
                };
            };
        };
    };
    get_schedule_from_db: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VUP 的 mid */
                mid: number;
                /** @description 年 */
                year: number;
                /** @description 周序号（ISO） */
                week: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指定周的日程表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null | components["schemas"]["ScheduleDto"];
                };
            };
        };
    };
    get_all_vup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VUP列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VupDto"][];
                };
            };
        };
    };
    get_all_vup_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VUP 元信息列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VupMetaDto"][];
                };
            };
        };
    };
    transform_latest_schedule_to_live_records: {
        parameters: {
            query?: {
                /**
                 * @description 模型名称（可选）。
                 * @example kimi-k2.5
                 */
                model?: string;
            };
            header?: never;
            path: {
                /** @description VUP 的 mid */
                mid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 转换并持久化后的记录 ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string | null;
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
